### ISSUE TITLE
Xkeeb Icon

### ISSUE THREAD

**Issue by ergtrewtg** [perryMELENOHRST/XKeeb#10]
I noticed your project after trying to find a conventional way to use Xbox Cloud Gaming with a keyboard and mouse, and thought this was pretty cool. I wanted to polish up my illustrator skills, so I designed a project logo of sorts. Feel free to do whatever you want with it
https://imgur.com/a/5waFAlH
:)

**Comment by luke-e-gibson** [comment]
Thank you for the logo I will add this to the readme and make this them main extension icon
